hnginternship5/ziki

landing-page.php, light-timeline2.php
=> Dragonblade

blog-detail-dark.php
I removed the font awesome link, and then added the svg icon for subscribe. That's the only icon that was from font awesome
=> Fixed blog details page

assets/css/light-theme.css, timeline.php
A simple version of the theme transition for the timeline page. This feature has not yet been set up in the settings page so I have included a simple "Toggle theme" button at the top-left corner of the timeline page. Clicking the button transitions the theme. The transition was achieved using CSS variables and a `.dark` class on the `body` element to signify the different colors for each theme. See screenshots below.
=> Theme transitions for timeline page

assets/css/contact-us.css, contact-us.php
The dark theme for contact us page
=> contact-us

assets/css/draft.css, assets/css/draft_light.css, draft.html
Adds light theme for Drafts Page
N/B: Opens Sans Font on Figma and Google Fonts are not Similar. Also No header and Footer
=> Added Drafts Page Light theme

assets/css/mobile-profile-user-setting.css, assets/css/profile-user-setting.css, mobile-user-profile-setting.php, user-profile-setting.php
=> white theme mobile user profile setting page created

assets/css/rssfeed-light.css, assets/img/Ellipse-green.svg, assets/img/Ellipse-purple.svg, assets/img/Ellipse-red.svg, assets/img/Ellipse-small.svg, feeds.php
Changed more of the icons font awesome to the exported svg from the design.
=> Changed more of the icons from font awesome.

assets/css/draft.css
Switches the theme of the dark page when the dark class is appended to elements
=> Added Draft Page Dark Theme

landing_page.php
Landing page with new figma redesign.
=> Modified Landing page FE

profile-mobile.html
This is the html of the mobile-profile page
=> mobile-profile page

mobile-profile.css
This is the css for the mobile-profile page
=> mobile-profile css

index.php
=> Modified Login Button

index.php, timeline.php
This should resolve most error and breakings on pages.
=> Fix: Cloning integration fix to staging 

index.php, timeline.php
This reverts commit 932ec1d7a801e4a0376e7b088dd4fa1cfd8ceb5f.
=> Revert "new readmore (#134)"

auth.php
Fix: Rectifying Auth.php page
Feature: removed unwanted text from the base of the auth.php page and also made the the buttons clickable
* It fixes the button issue
* When I click on any part of the social button, it takes you to the authentication page
* click on any of the button
* previous screenshot
* current screenshot
=> Fix : Rectifying Auth.php page

Authentication/auth/composer.json, Authentication/auth/composer.lock, Authentication/auth/fbook.php, Authentication/auth/googleinit.php, Authentication/auth/settings.json, home.php
Added vendor folder to test auth.php
=> Added vendor folder to test auth.php

auth.php, header.php, index.php, timeline.php
The auth.php is no longer a page but a file included in the index.php file to create the required modal 
functionality for login.
Timeline.php is now made to be responsive with its css code written as an internal css within the header.php file.
auth.php now works with index.php while timeline.php works with header.php and some code in the base.css
In the base.css line 254 - 341 only was adjusted because of necessity for the new modal to appear and function well.
=> TIMELINE PAGE AND AUTH FUNCTIONALITY UPDATED

index.php
* It makes the landing page responsive
* When the landing page is used across devices, it is responsive
* Right click on the landing page, click 'inspect element' and select any device to test.
=> Fix: Making the landing page responsive Feature: making the landing page, when the guest is not signed it, responsive across devices.

user-profile-setting.php
Removed homepage link and replaced it with logo and fixed appearances on some viewports
=> Profile setting page modified

assets/css/base.css
**What does this PR do?**
It adds the auth modal CSS to `base.css`.
**Testing**
Visit localhost:8000 and click on the login button to see the styled modal.
=> Add auth CSS to base.css

index.php
* It makes the landing page responsive
* It fixes one of the FE bugs: user avatar showing up when the login btn is clicked
=> Fix: Making the landing page responsive and fixing the icon showing up when login btn is clicked bug

user-profile-setting.php
=> User Profile Settings Updated
